version: "3.7"

services:
  crossfeed-web:
    build: .
    volumes:
      - ./:/app
      - /var/spool/cron/crontabs/:/var/spool/cron/crontabs/
    entrypoint: ["/bin/bash", "./start-server.sh", "${NODE_ENV}"]
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4599:4567-4599"
      - "4600:8080"
    volumes:
      - ./aws-dev:/docker-entrypoint-initaws.d

volumes:
  db-data:
